version: '3.8'

services:
  db:
    image: postgres:16
    container_name: portdb
    environment:
      POSTGRES_DB: portrisks
      POSTGRES_USER: portuser
      POSTGRES_PASSWORD: portpass
    ports:
      - "5432:5432"
    volumes:
      - portdb_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  portdb_data: