// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PortRiskMonitor.Infrastructure.Data;

#nullable disable

namespace PortRiskMonitor.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260516141841_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.7");

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.Alert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("KriDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<string>("KriName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("TriggerValue")
                        .HasColumnType("REAL");

                    b.Property<DateTime>("TriggeredAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KriDefinitionId");

                    b.HasIndex("ResolvedAt")
                        .HasDatabaseName("IX_Alerts_ResolvedAt");

                    b.ToTable("Alerts");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ClassName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long>("DurationMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("ExecutedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("MethodName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Permissions")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Success")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserIdentifier")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExecutedAt")
                        .HasDatabaseName("IX_AuditLogs_ExecutedAt");

                    b.HasIndex("UserIdentifier")
                        .HasDatabaseName("IX_AuditLogs_UserIdentifier");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.KriDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("FormulaLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<double>("GreenMax")
                        .HasColumnType("REAL");

                    b.Property<bool>("HigherIsWorse")
                        .HasColumnType("INTEGER");

                    b.Property<double>("MockBaseline")
                        .HasColumnType("REAL");

                    b.Property<string>("MockPattern")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<double>("MockVariance")
                        .HasColumnType("REAL");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("BLOB")
                        .HasDefaultValueSql("randomblob(8)");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<double>("Weight")
                        .HasColumnType("REAL");

                    b.Property<double>("YellowMax")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("IX_KriDefinitions_Name");

                    b.ToTable("KriDefinitions");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.KriReading", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsSimulated")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("KriDefinitionId")
                        .HasColumnType("TEXT");

                    b.Property<double>("NormalizedScore")
                        .HasColumnType("REAL");

                    b.Property<string>("RiskLevel")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("TEXT");

                    b.Property<double>("Value")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("KriDefinitionId", "Timestamp")
                        .HasDatabaseName("IX_KriReadings_KriId_Timestamp");

                    b.ToTable("KriReadings");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.Alert", b =>
                {
                    b.HasOne("PortRiskMonitor.Infrastructure.Entities.KriDefinition", "KriDefinition")
                        .WithMany("Alerts")
                        .HasForeignKey("KriDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KriDefinition");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.KriReading", b =>
                {
                    b.HasOne("PortRiskMonitor.Infrastructure.Entities.KriDefinition", "KriDefinition")
                        .WithMany("Readings")
                        .HasForeignKey("KriDefinitionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KriDefinition");
                });

            modelBuilder.Entity("PortRiskMonitor.Infrastructure.Entities.KriDefinition", b =>
                {
                    b.Navigation("Alerts");

                    b.Navigation("Readings");
                });
#pragma warning restore 612, 618
        }
    }
}
